#!/usr/bin/env python3
from pathlib import Path

CURRENT_DIR = Path(__file__).parent


for path in CURRENT_DIR.rglob("*"):
    if ".git" not in path.parts and path.is_file():
        print(f"=== {'/'.join(path.parts[-2:])} ===")
        print(path.read_text())
